[project]
name = "ai4cyber"
version = "0.1.0"
description = "Spam detection assignment project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"pandas",
	"scikit-learn",
	"numpy",
	"matplotlib",
	"seaborn",
	"nltk",
	"joblib",
	"tqdm",
	"datasets>=4.1.1",
]
